name: Terraform Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

env:
  TF_STATE_FILE: "terraform.tfstate"
  TF_DIR: "infrastructure"

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Export STATUSCAKE API Key
        run: echo "TF_VAR_statuscake_api_token=${{ secrets.STATUSCAKE_API_TOKEN }}" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Plan Terraform
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/features/*'
        run: terraform plan
        working-directory: ${{ env.TF_DIR }}

      - name: Apply Terraform
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: ${{ env.TF_DIR }}

      - name: Commit and Push Terraform State
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull
          git add $TF_DIR/$TF_STATE_FILE
          git commit -m "Update Terraform state [skip ci]" || echo "No changes to commit"
          git push